# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShankarMasala' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'CountryPickerView'
 pod 'Presentr'
 pod 'Alamofire'
 pod 'ReachabilitySwift'
 pod 'AlamofireNetworkActivityLogger', '~> 2.0'
 pod 'MagicalRecord'
 pod 'FastEasyMapping', '~> 1.2'
 pod 'IQKeyboardManager'
 pod 'SDWebImage'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Firebase/Crash'
 #pod 'ActionSheetPicker-3.0'
 pod 'CountdownLabel'
 pod 'LMGeocoder'
# pod 'PayUmoney_PnP'

  # Pods for ShankarMasala

end

